#pragma config(Sensor, S2, lightSensor, sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

void turn_left();
void turn_right();
void right_direction();
void left_direction();
int grid[9][7];
int currentColumn = 1;
int currentRow = 8;
int direction = 3;
void updateObstacleMap(int currentColumn, int currentRow, int direction);
	// 1 is north
	// 2 is south
	// 3 is east
	// 4 is west

//to help with our random turns, left = 1, right = 2;

int last_turn=1;
task main()
{
	// initialise our grid
	for (int i = 0; i < 4; i++)
	{
		for (int j = 0; i < 4; i ++)
		{
			grid[i][j] = 0;
		}
	}
	grid[8][3] = 99;

	
while(true)
{
nMotorEncoder[motorB] = 0;
nMotorEncoder[motorC] = 0;
nMotorEncoderTarget[motorB] = 180;
nMotorEncoderTarget[motorC] = 180;
motor[motorB] = 35;
motor[motorC] = 35;
while(nMotorRunState[motorC] != runStateIdle)
{
}
if(SensorValue(lightSensor) < 40 )
{
nMotorEncoder[motorB] = 0;
nMotorEncoder[motorC] = 0;

//turns 
if(last_turn==1)
{
	turn_left();
  left_direction();
	// change di and cell
	last_turn= rand()%2;

}
else
{
	turn_right();
	right_direction();
	last_turn= rand()%2;
}


while(nMotorRunState[motorC] != runStateIdle)
{
}
}
}
}

void turn_left()
{
nMotorEncoderTarget[motorB] = 187;
nMotorEncoderTarget[motorC] = -187;
motor[motorB] = 35;
motor[motorC] = -35;	
	
}

void turn_right()
{
nMotorEncoderTarget[motorB] = 187;
nMotorEncoderTarget[motorC] = -187;
motor[motorB] = -35;
motor[motorC] = 35;	

updateObstacleMap(currentColumn, currentRow,  direction);
	
}

void right_direction()
{
	if (direction == 1)
	{
		direction=2;
	}
	else if (direction == 4)
	{
		direction=1;
	}
	else if (direction == 3)
	{	
		direction=4;
	}
	else if (direction == 2)
	{	
		direction = 3;
	}
	
}

void left_direction()
{

if (direction == 1)
{
direction=4;
}
else if (direction == 4)
{
direction=3;
}
else if (direction == 3)
{
direction=2;
}
else if (direction == 2)
{
direction = 1;
}
}

void updateObstacleMap(int currentColumn, int currentRow, int direction)
{
	if (direction == 1)
		{
			//Facing north, so row above, same column is black
			grid[currentColumn][currentRow+1] = 1;

		}
	else if (direction == 2)
		{
			//Facing south, so row below, same column is black
			grid[currentColumn][currentRow-1] = 1;
		}
	else if (direction == 3)
		{
			//Facing east, so same row, next column is black
			grid[currentColumn+1][currentRow] = 1;
		}
	else
		{
			//Facing west, so same row, previous column is black
			grid[currentColumn-1][currentRow] = 1;
		}
}
